# Conexão com o banco MySQL
spring.datasource.url=jdbc:mysql://136.117.188.200:3306/gsw_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=chronosapi
spring.datasource.password=Bolsonaro#22
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

